//! Mocked integration test for the DeepSeek adapter.
//!
//! Spins up a `wiremock` server that pretends to be DeepSeek's
//! OpenAI-compatible chat-completions endpoint, points the adapter at
//! it, and asserts the full dispatch → wait → succeeded cycle. The real
//! `api.deepseek.com` is NEVER hit — `DeepSeekConfig::api_endpoint`
//! exists precisely so this test can swap it.

use std::collections::HashMap;
use std::time::Duration;

use serde_json::{json, Value};
use tempfile::TempDir;
use wiremock::matchers::{body_partial_json, header, method, path};
use wiremock::{Mock, MockServer, ResponseTemplate};

use evy_core::{Mandate, MandateId, PolicyMode, Provider, ProviderKind, WorkerStatus};
use evy_providers::{DeepSeekConfig, DeepSeekProvider};

const MODEL_RESPONSE_BODY: &str = "// generated by deepseek\nfn hello() {}\n";

fn fixture_config(server_url: &str, output_dir: std::path::PathBuf) -> DeepSeekConfig {
    DeepSeekConfig {
        api_endpoint: server_url.to_string(),
        api_key: "TESTKEY".to_string(),
        model: "deepseek-chat".to_string(),
        policy_mode: PolicyMode::Trusted,
        timeout_secs: 30,
        output_dir,
    }
}

fn fixture_mandate() -> Mandate {
    Mandate {
        id: MandateId::new(),
        provider: ProviderKind::DeepSeek,
        goal: "emit a hello function".to_string(),
        context: "Phase 3 Slice F integration test.".to_string(),
        deliverable: "rust source for a no-op `hello` fn".to_string(),
        done_when: vec!["file written to output_dir".to_string()],
        constraints: vec!["no external dependencies".to_string()],
        policy_mode: PolicyMode::Trusted,
        timeout: Some(Duration::from_secs(5)),
        metadata: HashMap::new(),
    }
}

fn mock_success_response() -> Value {
    json!({
        "id": "chatcmpl-mock",
        "object": "chat.completion",
        "created": 1,
        "model": "deepseek-chat",
        "choices": [{
            "index": 0,
            "message": {"role": "assistant", "content": MODEL_RESPONSE_BODY},
            "finish_reason": "stop",
        }],
        "usage": {"prompt_tokens": 1, "completion_tokens": 1, "total_tokens": 2}
    })
}

#[tokio::test]
async fn dispatch_then_wait_writes_deliverable_and_succeeds() {
    let server = MockServer::start().await;

    // The Mock asserts both auth header presence (so the bearer token
    // path is exercised) and the OpenAI-shape `model` field in the body
    // (so a wire-format regression in compose_chat_request would fail
    // here, not just in the unit-level golden).
    Mock::given(method("POST"))
        .and(path("/chat/completions"))
        .and(header("Authorization", "Bearer TESTKEY"))
        .and(body_partial_json(
            json!({"model": "deepseek-chat", "stream": false}),
        ))
        .respond_with(ResponseTemplate::new(200).set_body_json(mock_success_response()))
        .expect(1)
        .mount(&server)
        .await;

    let tmp = TempDir::new().expect("tempdir");
    let provider = DeepSeekProvider::with_config(fixture_config(&server.uri(), tmp.path().into()));
    let mandate = fixture_mandate();

    let worker = provider
        .dispatch(&mandate)
        .await
        .expect("dispatch must succeed against mock");
    let worker_id = worker.id();
    assert_eq!(worker.mandate_id(), mandate.id);

    let final_status = worker.wait().await.expect("wait must succeed");
    assert_eq!(final_status, WorkerStatus::Succeeded);

    let expected_path = tmp.path().join(format!("{}.md", worker_id.0.simple()));
    let contents = std::fs::read_to_string(&expected_path).unwrap_or_else(|e| {
        panic!(
            "deliverable not written to {}: {e}",
            expected_path.display()
        )
    });
    assert_eq!(contents, MODEL_RESPONSE_BODY);
}

#[tokio::test]
async fn dispatch_surfaces_http_error_as_failed_status() {
    let server = MockServer::start().await;

    Mock::given(method("POST"))
        .and(path("/chat/completions"))
        .respond_with(ResponseTemplate::new(401).set_body_json(json!({
            "error": {"message": "invalid api key", "type": "authentication_error"}
        })))
        .mount(&server)
        .await;

    let tmp = TempDir::new().expect("tempdir");
    let provider = DeepSeekProvider::with_config(fixture_config(&server.uri(), tmp.path().into()));
    let mandate = fixture_mandate();

    let worker = provider.dispatch(&mandate).await.expect("dispatch ok");
    let final_status = worker.wait().await.expect("wait ok");
    match final_status {
        WorkerStatus::Failed(reason) => {
            assert!(
                reason.contains("401"),
                "reason should include status: {reason}"
            );
        }
        other => panic!("expected Failed, got {other:?}"),
    }

    // No deliverable should have been written on failure.
    let expected_path = tmp.path().join(format!("{}.md", worker.id().0.simple()));
    assert!(
        !expected_path.exists(),
        "no file should be written when HTTP fails: {}",
        expected_path.display()
    );
}

#[tokio::test]
async fn cancel_transitions_worker_to_cancelled() {
    let server = MockServer::start().await;

    // Delay the response well past the cancel call so the in-flight
    // future is the one observing the cancel.
    Mock::given(method("POST"))
        .and(path("/chat/completions"))
        .respond_with(
            ResponseTemplate::new(200)
                .set_body_json(mock_success_response())
                .set_delay(Duration::from_secs(5)),
        )
        .mount(&server)
        .await;

    let tmp = TempDir::new().expect("tempdir");
    let provider = DeepSeekProvider::with_config(fixture_config(&server.uri(), tmp.path().into()));
    let mandate = fixture_mandate();

    let worker = provider.dispatch(&mandate).await.expect("dispatch ok");

    // Give the spawned task a moment to actually issue the request so
    // we're cancelling the in-flight HTTP future, not a not-yet-started
    // dispatch. 50ms is enough on a loaded laptop; we then poll.
    tokio::time::sleep(Duration::from_millis(50)).await;

    worker.cancel().await.expect("cancel ok");

    // wait() should now return Cancelled (well before the 5s upstream
    // delay would have completed).
    let deadline = std::time::Instant::now() + Duration::from_secs(2);
    loop {
        match worker.status().await.expect("status ok") {
            WorkerStatus::Cancelled => break,
            WorkerStatus::Running | WorkerStatus::Pending => {
                if std::time::Instant::now() >= deadline {
                    panic!("worker did not reach Cancelled within 2s");
                }
                tokio::time::sleep(Duration::from_millis(20)).await;
            }
            other => panic!("expected Cancelled, got {other:?}"),
        }
    }
}

#[tokio::test]
async fn healthcheck_against_mock_models_endpoint_succeeds_on_200() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/models"))
        .and(header("Authorization", "Bearer TESTKEY"))
        .respond_with(ResponseTemplate::new(200).set_body_json(json!({
            "object": "list",
            "data": [{"id": "deepseek-chat", "object": "model"}]
        })))
        .expect(1)
        .mount(&server)
        .await;

    let tmp = TempDir::new().expect("tempdir");
    let provider = DeepSeekProvider::with_config(fixture_config(&server.uri(), tmp.path().into()));
    provider
        .healthcheck()
        .await
        .expect("healthcheck must pass against a 200 from /models");
}

#[tokio::test]
async fn healthcheck_surfaces_auth_failure() {
    let server = MockServer::start().await;

    Mock::given(method("GET"))
        .and(path("/models"))
        .respond_with(ResponseTemplate::new(401))
        .mount(&server)
        .await;

    let tmp = TempDir::new().expect("tempdir");
    let provider = DeepSeekProvider::with_config(fixture_config(&server.uri(), tmp.path().into()));
    let err = provider
        .healthcheck()
        .await
        .expect_err("healthcheck must fail on 401");
    assert!(err.to_string().contains("401"));
}
